# Generated by Django 5.2.15 on 2026-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Request', 'verbose_name_plural': 'Admin Requests'},
        ),
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dispute', 'verbose_name_plural': 'Disputes'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='AED', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('Asia/Dubai', 'Dubai (GST, UTC+4)'), ('Asia/Abu_Dhabi', 'Abu Dhabi (GST, UTC+4)'), ('Asia/Sharjah', 'Sharjah (GST, UTC+4)'), ('Asia/Kolkata', 'India (IST, UTC+5:30)'), ('Europe/London', 'London (GMT, UTC+0)'), ('US/Eastern', 'Eastern (EST/EDT, UTC-5/-4)'), ('US/Central', 'Central (CST/CDT, UTC-6/-5)'), ('US/Mountain', 'Mountain (MST/MDT, UTC-7/-6)'), ('US/Pacific', 'Pacific (PST/PDT, UTC-8/-7)'), ('Europe/Paris', 'Central Europe (CET, UTC+1)')], default='Asia/Dubai', max_length=50),
        ),
    ]
