# Generated by Django 5.2.15 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_email_verified_userprofile_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='categories',
            field=models.CharField(blank=True, default='', help_text='Skill categories, comma-separated', max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Custom skill tags, comma-separated', max_length=500),
        ),
    ]
