# Generated by Django 5.2.15 on 2026-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teacher_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('Asia/Dubai', 'Dubai (GST, UTC+4)'), ('Asia/Abu_Dhabi', 'Abu Dhabi (GST, UTC+4)'), ('Asia/Sharjah', 'Sharjah (GST, UTC+4)'), ('Asia/Kolkata', 'India (IST, UTC+5:30)'), ('Asia/Karachi', 'Karachi (PKT, UTC+5)'), ('Europe/London', 'London (GMT, UTC+0)'), ('US/Eastern', 'Eastern (EST/EDT, UTC-5/-4)'), ('US/Central', 'Central (CST/CDT, UTC-6/-5)'), ('US/Mountain', 'Mountain (MST/MDT, UTC-7/-6)'), ('US/Pacific', 'Pacific (PST/PDT, UTC-8/-7)'), ('Europe/Paris', 'Central Europe (CET, UTC+1)')], default='Asia/Dubai', max_length=50),
        ),
    ]
