# Generated by Django 4.2.29 on 2026-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_teacher_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='session_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('60', '60 minutes'), ('both', 'Both (30 and 60 minutes)')], default='60', help_text='Allowed session durations for booking', max_length=10),
        ),
    ]
