# Generated by Django 5.2.15 on 2026-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_thread_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet'), ('mock', 'Mock Checkout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('paid_mock', 'Paid Mock'), ('holding_mock', 'Holding Mock'), ('failed_mock', 'Failed Mock'), ('refunded_mock', 'Refunded Mock'), ('released_mock', 'Released Mock')], default='pending', max_length=20),
        ),
    ]
