# Generated by Django 5.2.15 on 2026-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='session_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('60', '60 minutes')], default='60', help_text='Allowed session durations for booking', max_length=10),
        ),
    ]
